version: '3'
services:
  cs_redis_m1:
    image: redis:latest
    container_name: cs_redis_m1
    hostname: cs_redis_m1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16401:16401"
      - "26401:26401"
    volumes:
      - /content/cs/redis/masters/data-01:/data
      - /content/cs/redis/masters/logs-01:/logs
      - /content/cs/redis/masters/redis-01.conf:/usr/local/etc/redis/redis.conf
  cs_redis_m2:
    image: redis:latest
    container_name: cs_redis_m2
    hostname: cs_redis_m2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16402:16402"
      - "26402:26402"
    volumes:
      - /content/cs/redis/masters/data-02:/data
      - /content/cs/redis/masters/logs-02:/logs
      - /content/cs/redis/masters/redis-02.conf:/usr/local/etc/redis/redis.conf
  cs_redis_m3:
    image: redis:latest
    container_name: cs_redis_m3
    hostname: cs_redis_m3
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16403:16403"
      - "26403:26403"
    volumes:
      - /content/cs/redis/masters/data-03:/data
      - /content/cs/redis/masters/logs-03:/logs
      - /content/cs/redis/masters/redis-03.conf:/usr/local/etc/redis/redis.conf
  cs_redis_m4:
    image: redis:latest
    container_name: cs_redis_m4
    hostname: cs_redis_m4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16404:16404"
      - "26404:26404"
    volumes:
      - /content/cs/redis/masters/data-04:/data
      - /content/cs/redis/masters/logs-04:/logs
      - /content/cs/redis/masters/redis-04.conf:/usr/local/etc/redis/redis.conf
  cs_redis_m5:
    image: redis:latest
    container_name: cs_redis_m5
    hostname: cs_redis_m5
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16405:16405"
      - "26405:26405"
    volumes:
      - /content/cs/redis/masters/data-05:/data
      - /content/cs/redis/masters/logs-05:/logs
      - /content/cs/redis/masters/redis-05.conf:/usr/local/etc/redis/redis.conf
