version: '3'
services:
  cs_rabbit:
    image: cs_rabbitmq:latest
    container_name: cs_rabbitmq
    hostname: cs_rabbit
    build: .
    ports:
      - "25672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=SUPER_SECRET_USER_HERE
      - RABBITMQ_DEFAULT_PASS=SUPER_SECRET_PASS_HERE
      - RABBITMQ_HIPE_COMPILE=1
    volumes:
      - /content/cs/rabbitmq:/var/lib/rabbitmq
