version: '2'
services:
  cs_rabbit:
    image: rabbitmq:3-management
    container_name: cs_rabbitmq
    hostname: cs_rabbitmq
    build: .
    ports:
      - "25672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=supremelygood
      - RABBITMQ_DEFAULT_PASS=supremelygood
