FROM rabbitmq:3-management
MAINTAINER Caesar Kabalan <caesar.kabalan@gmail.com>

RUN rabbitmq-plugins enable --offline rabbitmq_sharding rabbitmq_consistent_hash_exchange rabbitmq_management_visualiser rabbitmq_shovel rabbitmq_shovel_management
